---
title: "Spotify Wrapped"
author: "Julie Deckers"
date: "2/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(spotifyr)

Julie <- get_playlist_audio_features("","37i9dQZF1EM27HE4pdYYcz")
Hemke <- get_playlist_audio_features("","37i9dQZF1EMgeVFiZwhb4Z")
Fleur <- get_playlist_audio_features("","37i9dQZF1EMd6LXIgrTylx")

Spotify_Wrapped <-
  bind_rows(
    Julie %>% mutate(category = "Julie"),
    Hemke %>% mutate(category = "Hemke"),
    Fleur %>% mutate(category = "Fleur")
  )


Spotify_Wrapped %>%                    
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  ) %>%
  ggplot(                     
    aes(
      x = valence,
      y = energy,
      size = loudness,
      colour = mode
    )
  ) +
  geom_point() +              
  geom_rug(size = 0.1) +      
  geom_text(                  
    aes(
      x = valence,
      y = energy,
      label = label
    ),
    data = 
      tibble(
        label = c( ""),
        valence = c(0.090, 0.123),
        energy = c(0.101, 0.967)
      ),
    colour = "black",         
    size = 3,                 
    hjust = "left",           
    vjust = "bottom",         
    nudge_x = -0.05,          
    nudge_y = 0.02            
  ) +
  facet_wrap(~category) +     
  scale_x_continuous(         
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),   
    minor_breaks = NULL       
  ) +
  scale_y_continuous(         
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),
    minor_breaks = NULL
  ) +
  scale_colour_brewer(       
    type = "qual",            
    palette = "Paired"        
  ) +
  scale_size_continuous(      
    trans = "exp",            
    guide = "none"            
  ) +
  theme_light() +            
  labs(                       
    x = "Valence",
    y = "Energy",
    colour = "Mode"
  )



```


